WebStoreKURS/Controllers/AdditionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStoreKURS.Data;
using WebStoreKURS.Data.Interfaces;
using WebStoreKURS.Data.Models;

namespace WebStoreKURS.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdditionController : Controller
    {
        private readonly AppDBContent appDBContent;
        private readonly IAllParts allParts;
        private readonly IPartsCategory allCategories;

        public AdditionController(AppDBContent app, IAllParts allparts, IPartsCategory ipartscat) 
        {
            appDBContent = app;
            allParts = allparts;
            allCategories = ipartscat;
        }
        [HttpGet]
        [Authorize]
        public IActionResult addPart()
        {
            return View();
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult addPart(Parts part)
        {
            Parts partToAdd = new Parts();
            partToAdd.name = part.name;
            partToAdd.isavailable = part.isavailable;
            partToAdd.isFavourite = part.isFavourite;
            partToAdd.shortDesc = part.shortDesc;
            partToAdd.longDesc = part.longDesc;
            partToAdd.price = part.price;
            partToAdd.img = part.img;
            partToAdd.categoryID = part.categoryID;

            IEnumerable<Categories> categories = null;
            categories = allCategories.AllCategories.OrderBy(i => i.id);
            switch(partToAdd.categoryID)
            {
                case 1:
                    partToAdd.Category = allCategories.AllCategories.ElementAt(0);
                    break;
                case 2:
                    partToAdd.Category = appDBContent.Category.ElementAt(1);
                    break;
                case 3:
                    partToAdd.Category = appDBContent.Category.ElementAt(2);
                    break;
                
            }
            if (partToAdd.categoryID!=null&& partToAdd.Category != null)
            {
                appDBContent.Part.Add(partToAdd);
                appDBContent.SaveChanges();
                return RedirectToAction("Completion");
            }
            else
            {
                return RedirectToAction("Failure");
            }
            return View(partToAdd);
        }

        public IActionResult Completion()
        {
            ViewBag.Message = "Действие завершено";
            return View();
        }
        public IActionResult Failure()
        {
            ViewBag.Message = "Что-то пошло не так!";
            return View();
        }
    }
}

WebStoreKURS/Controllers/PartsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStoreKURS.Data;
using WebStoreKURS.Data.Interfaces;
using WebStoreKURS.Data.Models;
using WebStoreKURS.ViewModels;

namespace WebStoreKURS.Controllers
{
    public class PartsController : Controller
    {
        private readonly IAllParts allParts;
        private readonly IPartsCategory allCategories; 

        public PartsController(IAllParts iallparts, IPartsCategory ipartscat) // передача интерфейсов сюда равнозначна передаче класса с которым он связан (startup.cs)
        {
            allParts = iallparts;
            allCategories = ipartscat;
        }
        [Route("Parts/List")]
        [Route("Parts/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Parts> parts = null;
            string currCategory = "";
            if(string.IsNullOrEmpty(category))
            {
                parts = allParts.AllParts.OrderBy(i => i.id);
            }
            else
            {
                if(string.Equals("gpu", category, StringComparison.OrdinalIgnoreCase))
                {
                    parts = allParts.AllParts.Where(i => i.Category.categoryname.Equals("Графическая карта")).OrderBy(i => i.id);
                }
                else if (string.Equals("processor", category, StringComparison.OrdinalIgnoreCase))
                {
                    parts = allParts.AllParts.Where(i => i.Category.categoryname.Equals("Процессор")).OrderBy(i => i.id);
                }
                else if (string.Equals("ram", category, StringComparison.OrdinalIgnoreCase))
                {
                    parts = allParts.AllParts.Where(i => i.Category.categoryname.Equals("Оперативная память")).OrderBy(i => i.id);
                }

                currCategory = _category;

            }
            var partObj = new PartsListViewModel
            {
                AllParts = parts,
                currCategory = currCategory
            };

            ViewBag.Title = "Список товаров";

            return View(partObj);
        }

    }
}

WebStoreKURS/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStoreKURS.Data.Interfaces;
using WebStoreKURS.Data.Models;
using WebStoreKURS.Data.Repository;
using WebStoreKURS.ViewModels;

namespace WebStoreKURS.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllParts _partRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllParts partRep, ShopCart shopCart)
        {
            _partRep = partRep;
            _shopCart = shopCart;
        }
        public ViewResult ShopCartPage()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        }
        public RedirectToActionResult addToCart(int id)
        {
            var item = _partRep.AllParts.FirstOrDefault(i => i.id == id);
            if(item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("ShopCartPage");
        }
        public RedirectToActionResult removeFromCart(int id)
        {
            var items = _shopCart.GetShopItems();
            _shopCart.listShopItems = items;
            var item = _shopCart.listShopItems.FirstOrDefault(i => i.id == id);
            if(item != null)
            {
                _shopCart.RemoveFromCart(item);
            }
            return RedirectToAction("ShopCartPage");
        }
    }
}

WebStoreKURS/Views/Shared/AllParts.cshtml
@model Parts

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2>@Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Цена: @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">В корзину</a></p>
</div>

WebStoreKURS/Views/Shared/NotFound.cshtml
@{ 
    ViewBag.Title = "Not Found";
}

<h2>@ViewBag.ErrorMessage</h2>
<a asp-action="TopSellers", asp-controller="Home">
    Нажмите сюда чтобы вернуться на главную страницу
</a>

WebStoreKURS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@inject SignInManager<ApplicationUser> signInManager;
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Курсовая</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="TopSellers">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Parts" asp-action="List" asp-route-category="">Все товары</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-controller="Parts" asp-action="List" asp-route-category="gpu">Графические карты</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-controller="Parts" asp-action="List" asp-route-category="processor">Процессоры</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-controller="Parts" asp-action="List" asp-route-category="ram">Оперативная память</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/ShopCartPage">Корзина</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Administration" asp-action="ListUsers" asp-route-category="">Список пользователей</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Administration" asp-action="ListRoles" asp-route-category="">Список ролей</a>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item ml-auto">
                                <form method="post" asp-action="Logout" asp-controller="Account">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                        Выход из @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ml-auto">
                                <a class="nav-link" asp-controller="Account" asp-action="Register">Регистрация</a>
                            </li>
                            <li class="nav-item ml-auto">
                                <a class="nav-link" asp-controller="Account" asp-action="Login">Вход</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Вернуться наверх</a></p>
        <p>©2022 Company, Inc. · <a href="#">Соглашение</a></p>
        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
        {
            <p><a asp-controller="Addition" asp-action="addPart">Добавить элемент</a></p>
        }
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>